build_script:
  build.bat

test: off

artifacts:
  - path: TodoBackendSuave.ServiceHost\bin\Release
    name: TodoBackendSuave.ServiceHost

deploy:
  - provider: Environment
    name: TodoBackend
    service_executable: TodoBackendSuave.ServiceHost.exe
    service_name: TodoBackendSuave